engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc
  csslint:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - '**.js'
exclude_paths:
- build/**/*
- test/**/*
