engines:
  eslint:
    enabled: true
    channel: 'eslint-3'
    checks:
      import/no-unresolved:
        enabled: false
  csslint:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - '**.js'
exclude_paths:
- build/**/*
- test/**/*
