/*
  name constants as NOUN_ACTION so that actions related
  by nouns will show up near each other in an alphabetized list
*/

export const AGENCIES_FETCHING = 'AGENCIES_FETCHING'
export const AGENCIES_RECEIVED = 'AGENCIES_RECEIVED'
export const AGENCY_FAILED = 'AGENCY_FAILED'
export const AGENCY_FETCHING = 'AGENCY_FETCHING'
export const AGENCY_RECEIVED = 'AGENCY_RECEIVED'

export const FILTER_RESET = 'FILTER_RESET'
export const FILTERS_UPDATE = 'FILTERS_UPDATE'

export const GLOSSARY_HIDE = 'GLOSSARY_HIDE'
export const GLOSSARY_SHOW = 'GLOSSARY_SHOW'
export const GLOSSARY_SHOW_TERM = 'GLOSSARY_SHOW_TERM'

export const MODAL_HIDE = 'MODAL_HIDE'
export const MODAL_SHOW = 'MODAL_SHOW'

export const NIBRS_FAILED = 'NIBRS_FAILED'
export const NIBRS_FETCHING = 'NIBRS_FETCHING'
export const NIBRS_RECEIVED = 'NIBRS_RECEIVED'

export const NIBRS_COUNTS_FAILED = 'NIBRS_COUNTS_FAILED'
export const NIBRS_COUNTS_FETCHING = 'NIBRS_COUNTS_FETCHING'
export const NIBRS_COUNTS_RECEIVED = 'NIBRS_COUNTS_RECEIVED'

export const SIDEBAR_HIDE = 'SIDEBAR_HIDE'
export const SIDEBAR_SHOW = 'SIDEBAR_SHOW'

export const SUMMARY_FAILED = 'SUMMARY_FAILED'
export const SUMMARY_FETCHING = 'SUMMARY_FETCHING'
export const SUMMARY_RECEIVED = 'SUMMARY_RECEIVED'

export const UCR_PARTICIPATION_FAILED = 'UCR_PARTICIPATION_FAILED'
export const UCR_PARTICIPATION_FETCHING = 'UCR_PARTICIPATION_FETCHING'
export const UCR_PARTICIPATION_RECEIVED = 'UCR_PARTICIPATION_RECEIVED'

export const UCR_REGION_FAILED = 'UCR_REGION_FAILED'
export const UCR_REGION_FETCHING = 'UCR_REGION_FETCHING'
export const UCR_REGION_RECEIVED = 'UCR_REGION_RECEIVED'

export const UCR_STATE_FAILED = 'UCR_STATE_FAILED'
export const UCR_STATE_FETCHING = 'UCR_STATE_FETCHING'
export const UCR_STATE_RECEIVED = 'UCR_STATE_RECEIVED'

export const POLICE_EMPLOYMENT_FAILED = 'POLICE_EMPLOYMENT_FAILED'
export const POLICE_EMPLOYMENT_FETCHING = 'POLICE_EMPLOYMENT_FETCHING'
export const POLICE_EMPLOYMENT_RECEIVED = 'POLICE_EMPLOYMENT_RECEIVED'

export const LEOKA_FAILED = 'LEOKA_FAILED'
export const LEOKA_FETCHING = 'LEOKA_FETCHING'
export const LEOKA_RECEIVED = 'LEOKA_RECEIVED'

export const SUMMARIZED_FAILED = 'SUMMARIZED_FAILED'
export const SUMMARIZED_FETCHING = 'SUMMARIZED_FETCHING'
export const SUMMARIZED_RECEIVED = 'SUMMARIZED_RECEIVED'
