/*
  name constants as NOUN_ACTION so that actions related
  by nouns will show up near each other in an alphabetized list
*/

export const AGENCY_FETCHING = 'AGENCY_FETCHING'
export const AGENCY_RECEIVED = 'AGENCY_RECEIVED'

export const FEEDBACK_HIDE = 'FEEDBACK_HIDE'
export const FEEDBACK_SHOW = 'FEEDBACK_SHOW'

export const FILTER_RESET = 'FILTER_RESET'
export const FILTERS_UPDATE = 'FILTERS_UPDATE'

export const GLOSSARY_HIDE = 'GLOSSARY_HIDE'
export const GLOSSARY_SHOW = 'GLOSSARY_SHOW'
export const GLOSSARY_SHOW_TERM = 'GLOSSARY_SHOW_TERM'

export const MODAL_HIDE = 'MODAL_HIDE'
export const MODAL_SHOW = 'MODAL_SHOW'

export const NIBRS_FAILED = 'NIBRS_FAILED'
export const NIBRS_FETCHING = 'NIBRS_FETCHING'
export const NIBRS_RECEIVED = 'NIBRS_RECEIVED'

export const SIDEBAR_HIDE = 'SIDEBAR_HIDE'
export const SIDEBAR_SHOW = 'SIDEBAR_SHOW'

export const SUMMARY_FETCHING = 'SUMMARY_FETCHING'
export const SUMMARY_RECEIVED = 'SUMMARY_RECEIVED'

export const UCR_PARTICIPATION_FAILURE = 'UCR_PARTICIPATION_FAILURE'
export const UCR_PARTICIPATION_FETCHING = 'UCR_PARTICIPATION_FETCHING'
export const UCR_PARTICIPATION_RECEIVED = 'UCR_PARTICIPATION_RECEIVED'
