applications:
- name: crime-data-explorer-staging
  buildpack: nodejs_buildpack
  memory: 512M
  host: crime-data-explorer-staging
  domain: fr.cloud.gov
services:
- crime-data-api-creds
env:
  NODE_ENV: 'production'
